version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/repo
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/chown.sh
      timeout: 30
      runas: root
    - location: scripts/deploy-frontend-website.sh
      timeout: 300
      runas: ec2-user
